algoritmo "VerificarNumero"
// Função : Verificar o Número
// Autor : felismino Chico
// Data : 05/12/2022
// Seção de Declarações 
var
   N: Inteiro
   Procedimento Verif(M: Inteiro)
   Inicio
         Escreva("Digite um Número: ")
         Leia(M)
         Se (M % 2 = 1) entao
            Escreva("O Número ", M, " é Ímpar.")
         senao
              Escreva("O Número ", M, " é Par.")
         FimSe
   FimProcedimento
inicio
      Verif(N)
fimalgoritmo
